# Generated by Django 5.1.3 on 2025-02-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_document_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ressources/videos'),
        ),
    ]
