# Generated by Django 5.1.3 on 2025-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_alter_video_options_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ressources/images'),
        ),
    ]
