# Generated by Django 5.1.3 on 2025-03-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0005_activite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ressources/videos'),
        ),
    ]
