# Generated by Django 5.1.3 on 2025-03-10 03:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0007_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
