# Generated by Django 5.1.3 on 2025-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0008_alter_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='libele',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
