# Generated by Django 5.1.3 on 2025-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0009_remove_video_description_video_libele'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
                ('url_media', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
