# Generated by Django 5.1.3 on 2025-03-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0010_publication_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication_media',
            old_name='created',
            new_name='created_on',
        ),
    ]
