# Generated by Django 5.1.3 on 2025-03-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0011_rename_created_publication_media_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_media',
            name='media',
            field=models.CharField(default='wuri', max_length=255),
        ),
    ]
