# Generated by Django 5.1.3 on 2025-03-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0012_publication_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_media',
            name='media',
            field=models.CharField(max_length=255),
        ),
    ]
