# Generated by Django 5.1.3 on 2025-03-11 10:42

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelsOfrres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='plaintes/appelsOffres')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('mission', tinymce.models.HTMLField(null=True)),
                ('niveau_etude', models.CharField(max_length=150)),
                ('niveau_experience', models.CharField(max_length=255)),
                ('competences_cles', models.CharField(max_length=255)),
                ('contrat_propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_recrutementt', to='offres.contrat')),
            ],
        ),
    ]
