# Generated by Django 5.1.3 on 2025-03-25 22:13

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaintes', '0002_alter_faq_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='glossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255, unique=True)),
                ('definition', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
