# Generated by Django 5.1.3 on 2025-03-26 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaintes', '0004_traitement_plainte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='traitement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plaintes.traitement'),
        ),
    ]
