# Generated by Django 5.1.3 on 2025-03-11 10:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
